package com.qg.smpt.web.model/test;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_time
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_remark
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_meal_fee
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String orderMealFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_pay_status
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String orderPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_dis_fee
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private Integer orderDisFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_pre_amount
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private Integer orderPreAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_sum
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private Integer orderSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_name
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_address
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_telephone
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String userTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_content
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    private String orderContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_time
     *
     * @return the value of order.order_time
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_time
     *
     * @param orderTime the value for order.order_time
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_remark
     *
     * @return the value of order.order_remark
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_remark
     *
     * @param orderRemark the value for order.order_remark
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_meal_fee
     *
     * @return the value of order.order_meal_fee
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getOrderMealFee() {
        return orderMealFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_meal_fee
     *
     * @param orderMealFee the value for order.order_meal_fee
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderMealFee(String orderMealFee) {
        this.orderMealFee = orderMealFee == null ? null : orderMealFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_pay_status
     *
     * @return the value of order.order_pay_status
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_pay_status
     *
     * @param orderPayStatus the value for order.order_pay_status
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderPayStatus(String orderPayStatus) {
        this.orderPayStatus = orderPayStatus == null ? null : orderPayStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_dis_fee
     *
     * @return the value of order.order_dis_fee
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public Integer getOrderDisFee() {
        return orderDisFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_dis_fee
     *
     * @param orderDisFee the value for order.order_dis_fee
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderDisFee(Integer orderDisFee) {
        this.orderDisFee = orderDisFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_pre_amount
     *
     * @return the value of order.order_pre_amount
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public Integer getOrderPreAmount() {
        return orderPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_pre_amount
     *
     * @param orderPreAmount the value for order.order_pre_amount
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderPreAmount(Integer orderPreAmount) {
        this.orderPreAmount = orderPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_sum
     *
     * @return the value of order.order_sum
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public Integer getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_sum
     *
     * @param orderSum the value for order.order_sum
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderSum(Integer orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_status
     *
     * @return the value of order.order_status
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_status
     *
     * @param orderStatus the value for order.order_status
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_name
     *
     * @return the value of order.user_name
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_name
     *
     * @param userName the value for order.user_name
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_address
     *
     * @return the value of order.user_address
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_address
     *
     * @param userAddress the value for order.user_address
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_telephone
     *
     * @return the value of order.user_telephone
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_telephone
     *
     * @param userTelephone the value for order.user_telephone
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_content
     *
     * @return the value of order.order_content
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public String getOrderContent() {
        return orderContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_content
     *
     * @param orderContent the value for order.order_content
     *
     * @mbggenerated Mon Jul 25 15:14:52 CST 2016
     */
    public void setOrderContent(String orderContent) {
        this.orderContent = orderContent == null ? null : orderContent.trim();
    }
}