package com.qg.smpt.web.model;

import com.qg.smpt.printer.model.BConstants;
import com.qg.smpt.printer.model.BOrder;
import com.qg.smpt.util.BytesConvert;

import java.util.Date;
import java.util.List;

/**
 * 订单
 * Created by tisong on 7/20/16.
 */
public final class Order {
    private int mpu;             //主控板id

    private List<Item> items;  //订单物品

    private byte[] data;
    private boolean isConvert = false;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_time
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_remark
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_meal_fee
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String orderMealFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_pay_status
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String orderPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_dis_fee
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private Integer orderDisFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_pre_amount
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private Integer orderPreAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_sum
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private Integer orderSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_name
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_address
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_telephone
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String userTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_content
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    private String orderContent;

    private String company;

    private String expectTime;

    public void setItems(List<Item> items) {
        this.items = items;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public void setExpectTime(String expectTime) {
        this.expectTime = expectTime;
    }

    public void setMpu(int mpu) {
        this.mpu = mpu;
    }

    public String getExpectTime() {
        return expectTime;
    }

    public void setConvert(boolean convert) {
        isConvert = convert;
    }

    public List<Item> getItems() {
        return items;
    }

    public String getCompany() {
        return company;
    }

    public int getMpu() {
        return mpu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_time
     *
     * @return the value of orders.order_time
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_time
     *
     * @param orderTime the value for orders.order_time
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_remark
     *
     * @return the value of orders.order_remark
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_remark
     *
     * @param orderRemark the value for orders.order_remark
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_meal_fee
     *
     * @return the value of orders.order_meal_fee
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getOrderMealFee() {
        return orderMealFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_meal_fee
     *
     * @param orderMealFee the value for orders.order_meal_fee
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderMealFee(String orderMealFee) {
        this.orderMealFee = orderMealFee == null ? null : orderMealFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_pay_status
     *
     * @return the value of orders.order_pay_status
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_pay_status
     *
     * @param orderPayStatus the value for orders.order_pay_status
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderPayStatus(String orderPayStatus) {
        this.orderPayStatus = orderPayStatus == null ? null : orderPayStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_dis_fee
     *
     * @return the value of orders.order_dis_fee
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public Integer getOrderDisFee() {
        return orderDisFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_dis_fee
     *
     * @param orderDisFee the value for orders.order_dis_fee
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderDisFee(Integer orderDisFee) {
        this.orderDisFee = orderDisFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_pre_amount
     *
     * @return the value of orders.order_pre_amount
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public Integer getOrderPreAmount() {
        return orderPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_pre_amount
     *
     * @param orderPreAmount the value for orders.order_pre_amount
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderPreAmount(Integer orderPreAmount) {
        this.orderPreAmount = orderPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_sum
     *
     * @return the value of orders.order_sum
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public Integer getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_sum
     *
     * @param orderSum the value for orders.order_sum
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderSum(Integer orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_name
     *
     * @return the value of orders.user_name
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_name
     *
     * @param userName the value for orders.user_name
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_address
     *
     * @return the value of orders.user_address
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_address
     *
     * @param userAddress the value for orders.user_address
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_telephone
     *
     * @return the value of orders.user_telephone
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_telephone
     *
     * @param userTelephone the value for orders.user_telephone
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_content
     *
     * @return the value of orders.order_content
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public String getOrderContent() {
        return orderContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_content
     *
     * @param orderContent the value for orders.order_content
     *
     * @mbggenerated Mon Jul 25 16:23:12 CST 2016
     */
    public void setOrderContent(String orderContent) {
        this.orderContent = orderContent == null ? null : orderContent.trim();
    }



    public byte[] getData() {
        if(!isConvert){

        }
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

    private int getTotalCost() {
        int c = 0;
        for(Item item : items) {
            c += item.getCost();
        }

        c += orderDisFee;
        c += Integer.getInteger(orderMealFee);
        setOrderPreAmount(c);
        c -= getOrderPreAmount();

        return c;
    }

    @Override
    public String toString() {
        StringBuffer buffer = new StringBuffer();
        buffer.append(company + "\n");
        buffer.append(userName + "\n");
        buffer.append("订单编号: " + getId() + "\n");
        buffer.append("下单时间: " + getOrderTime() + "\n");
        buffer.append("预计下单时间: " + getExpectTime() + "\n");
        buffer.append("备注: " + getOrderContent() + "\n");
        buffer.append("菜单名                                 数量               小计\n");
        for(Item item : items){
            buffer.append(item.toString() + "\n");
        }
        buffer.append("餐盒费: " + getOrderMealFee() + "\n");
        buffer.append("配送费: " + getOrderDisFee() + "\n");
        buffer.append("优惠额: " + getOrderPreAmount() + "\n");
        buffer.append("合 计: " + getOrderSum() + "\n");
        buffer.append("已付款" + "\n");
        buffer.append("顾客姓名: " + getUserName() + "\n");
        buffer.append("送餐地址: " + getUserAddress() + "\n");
        buffer.append("电话: " + getUserTelephone() + "\n");
//        buffer.append("商家地址: " + getFrom() + "\n");
//        buffer.append("联系方式: " + getShopContact() + "\n");
        return buffer.toString();

    }

    //Order对象转换为BOrder
    public BOrder orderToBOrder(short bulkId, short index) throws Exception{
        BOrder bo = new BOrder();

        //设置主控板id
        bo.setId(mpu);

        //设置时间戳
        bo.setSeconds((int)(System.currentTimeMillis()));

        //设置订单序号
        bo.setOrderNumber(id);

        //设置批次,批次内序号
        bo.setBulkId(bulkId);
        bo.setInNumber(index);

        //设置校验和和填充
        bo.setCheckNum((short)0);
        bo.setPadding0((short)0);

        //设置数据域,数据长度
        byte[] data = convertOrder();
        short length = (short)data.length;
        bo.setData(data);
        bo.setLength(length);

        //设置填充
        bo.setPadding1((short)0);
        bo.size = 28 + length;
        return bo;
    }

    //将订单内容转化为字节数组
    private byte[] convertOrder() throws Exception{
        //通过GB2312编码获取订单内容的字节数组
        byte[] orderB = this.toString().getBytes("gb2312");

        //获取订单内容的长度
        int length = orderB.length;

        //因为要字节对齐,以4字节为为单位,所以计算要填充多少位字节
        int fillLength = 4 - (length % 4);

        //创建字节数组,大小为订单数据长度  8主要是文本内容前后要各加4字节的头尾部信息
        byte[] data = new byte[length + 8 + fillLength];

        int pos = 0;

        //填充文本开始字符
        pos = BytesConvert.fillShort(BConstants.textStart,data,pos);

        //填充文本长度
        pos = BytesConvert.fillShort((short)(length + fillLength),data,pos);

        //填充文本数据
        pos = BytesConvert.fillByte(orderB, data, pos);

        //填充填充位
        pos  += (fillLength + 2);

        //填充文本结束字符
        pos = BytesConvert.fillShort(BConstants.textEnd, data, pos);

        return data;
    }


}