package com.qg.smpt.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_time
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_remark
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_meal_fee
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer orderMealFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_pay_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String orderPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_dis_fee
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer orderDisFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_pre_amount
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer orderPreAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_sum
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer orderSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_telephone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.client_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String clientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.client_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String clientAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.client_telephone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String clientTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_content
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String orderContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_time
     *
     * @return the value of orders.order_time
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_time
     *
     * @param orderTime the value for orders.order_time
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_remark
     *
     * @return the value of orders.order_remark
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_remark
     *
     * @param orderRemark the value for orders.order_remark
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_meal_fee
     *
     * @return the value of orders.order_meal_fee
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getOrderMealFee() {
        return orderMealFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_meal_fee
     *
     * @param orderMealFee the value for orders.order_meal_fee
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderMealFee(Integer orderMealFee) {
        this.orderMealFee = orderMealFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_pay_status
     *
     * @return the value of orders.order_pay_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_pay_status
     *
     * @param orderPayStatus the value for orders.order_pay_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderPayStatus(String orderPayStatus) {
        this.orderPayStatus = orderPayStatus == null ? null : orderPayStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_dis_fee
     *
     * @return the value of orders.order_dis_fee
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getOrderDisFee() {
        return orderDisFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_dis_fee
     *
     * @param orderDisFee the value for orders.order_dis_fee
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderDisFee(Integer orderDisFee) {
        this.orderDisFee = orderDisFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_pre_amount
     *
     * @return the value of orders.order_pre_amount
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getOrderPreAmount() {
        return orderPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_pre_amount
     *
     * @param orderPreAmount the value for orders.order_pre_amount
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderPreAmount(Integer orderPreAmount) {
        this.orderPreAmount = orderPreAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_sum
     *
     * @return the value of orders.order_sum
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_sum
     *
     * @param orderSum the value for orders.order_sum
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderSum(Integer orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_name
     *
     * @return the value of orders.user_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_name
     *
     * @param userName the value for orders.user_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_address
     *
     * @return the value of orders.user_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_address
     *
     * @param userAddress the value for orders.user_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_telephone
     *
     * @return the value of orders.user_telephone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_telephone
     *
     * @param userTelephone the value for orders.user_telephone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone == null ? null : userTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.client_name
     *
     * @return the value of orders.client_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.client_name
     *
     * @param clientName the value for orders.client_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.client_address
     *
     * @return the value of orders.client_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getClientAddress() {
        return clientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.client_address
     *
     * @param clientAddress the value for orders.client_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setClientAddress(String clientAddress) {
        this.clientAddress = clientAddress == null ? null : clientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.client_telephone
     *
     * @return the value of orders.client_telephone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getClientTelephone() {
        return clientTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.client_telephone
     *
     * @param clientTelephone the value for orders.client_telephone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setClientTelephone(String clientTelephone) {
        this.clientTelephone = clientTelephone == null ? null : clientTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_content
     *
     * @return the value of orders.order_content
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getOrderContent() {
        return orderContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_content
     *
     * @param orderContent the value for orders.order_content
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setOrderContent(String orderContent) {
        this.orderContent = orderContent == null ? null : orderContent.trim();
    }
}