package com.qg.smpt.model;

public class Printer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printer.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column printer.printer_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String printerStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printer.id
     *
     * @return the value of printer.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printer.id
     *
     * @param id the value for printer.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column printer.printer_status
     *
     * @return the value of printer.printer_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getPrinterStatus() {
        return printerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column printer.printer_status
     *
     * @param printerStatus the value for printer.printer_status
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setPrinterStatus(String printerStatus) {
        this.printerStatus = printerStatus == null ? null : printerStatus.trim();
    }
}