package com.qg.smpt.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_account
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_printers
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private Integer userPrinters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_logo
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_qrcode
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userQrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_store
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_phone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    private String userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_account
     *
     * @return the value of user.user_account
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_account
     *
     * @param userAccount the value for user.user_account
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_printers
     *
     * @return the value of user.user_printers
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public Integer getUserPrinters() {
        return userPrinters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_printers
     *
     * @param userPrinters the value for user.user_printers
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserPrinters(Integer userPrinters) {
        this.userPrinters = userPrinters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_logo
     *
     * @return the value of user.user_logo
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserLogo() {
        return userLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_logo
     *
     * @param userLogo the value for user.user_logo
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserLogo(String userLogo) {
        this.userLogo = userLogo == null ? null : userLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_qrcode
     *
     * @return the value of user.user_qrcode
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserQrcode() {
        return userQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_qrcode
     *
     * @param userQrcode the value for user.user_qrcode
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserQrcode(String userQrcode) {
        this.userQrcode = userQrcode == null ? null : userQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_store
     *
     * @return the value of user.user_store
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserStore() {
        return userStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_store
     *
     * @param userStore the value for user.user_store
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserStore(String userStore) {
        this.userStore = userStore == null ? null : userStore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_address
     *
     * @return the value of user.user_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_address
     *
     * @param userAddress the value for user.user_address
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_phone
     *
     * @return the value of user.user_phone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_phone
     *
     * @param userPhone the value for user.user_phone
     *
     * @mbggenerated Sat Apr 08 11:09:21 CST 2017
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }
}